[tool.bumpversion]
current_version = "0.6.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "manifest.v2.json"

[[tool.bumpversion.files]]
filename = "manifest.v3.json"

[[tool.bumpversion.files]]
filename = "package.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

[[tool.bumpversion.files]]
filename = "package-lock.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'
